'use strict';
const $=id=>document.getElementById(id);
const numberKeys=['strategy','capital','risk','rr','buffer','fee','slip','emaFast','emaMid','emaSlow','atrPeriod','adxMax','volumeFactor','lookback','bbPeriod','bbMult','rsiPeriod','rsiMin','rsiMax'];
const configKeys=[...numberKeys,'signalTF','trendTF','start','end','resistance','rsiFilter'];
const defaultConfig={strategy:1,signalTF:'auto',trendTF:'auto',start:'2021-01-01',end:'2026-09-30',capital:10000,risk:.25,rr:3,buffer:.2,fee:.1,slip:.02,resistance:true,emaFast:20,emaMid:50,emaSlow:200,atrPeriod:14,adxMax:20,volumeFactor:1.5,lookback:48,bbPeriod:20,bbMult:2,rsiPeriod:14,rsiFilter:false,rsiMin:30,rsiMax:70};
const names=Array.from($('strategy').options).map(o=>o.textContent.replace(/^\d+ · /,''));
const hints=['Откат к EMA20 внутри восходящего тренда на 4H.','Первый ретест пробитого уровня после всплеска объёма.','Пробой диапазона после сжатия Bollinger Bands.','Возврат над минимумом предыдущего дня.','Отскок от нижней границы при низком ADX.','Возврат к дневному VWAP после сильного отклонения.','Пробой максимума первых шести часов дня UTC.','Продолжение движения после импульса и консолидации.','Возврат над уровнем после неудачного пробоя вниз.','Отскок от EMA50 при восходящем дневном тренде.'];
const rules=[
'Цена выше старшей EMA, средняя EMA выше старшей на таймфрейме тренда. На таймфрейме сигналов касание быстрой EMA в последних 5 свечах и закрытие выше предыдущего максимума. Стоп под минимумом 5 свечей с буфером ATR.',
'Закрытие выше максимума предыдущих N свечей при объёме выше заданного множителя среднего за 20 свечей. В следующих 6 свечах первый ретест уровня с допуском буфера ATR и закрытием выше него. Стоп под свечой ретеста.',
'Ширина Bollinger на предыдущей свече ниже 20-го процентиля за предшествующие 180 значений. Закрытие выше максимума предыдущих 12 свечей при повышенном объёме. Стоп под пробойной свечой. Чистая цель не ниже 3,5R.',
'Минимум свечи ниже минимума предыдущего завершённого дня UTC, закрытие выше уровня. Нижняя тень занимает не меньше половины свечи. Стоп под минимумом сигнала. Максимум предыдущего дня должен находиться выше цели.',
'ADX ниже заданного порога. Минимум свечи находится в пределах буфера ATR от нижней границы предыдущих N свечей. Закрытие внутри диапазона, нижняя тень не меньше половины свечи. Цель — верхняя граница минус буфер ATR; вход только при достаточном чистом RR.',
'ADX ниже порога. Минимум свечи ниже дневного VWAP на 2 ATR, закрытие выше максимума предыдущей свечи. Стоп под минимумом последних 3 свечей. Цель — VWAP при сигнале; вход только при достаточном чистом RR.',
'После 06:00 и до 12:00 UTC закрытие пересекает вверх максимум диапазона 00:00–06:00. Повышенный объём и цена выше старшей EMA на таймфрейме тренда. Один исполненный вход в день. Стоп под пробойной свечой.',
'Рост за 3 свечи не меньше 2 ATR. Затем консолидация 3–8 свечей с коррекцией не глубже 50% импульса. Закрытие выше максимума консолидации. Стоп под её минимумом. Размер исходного импульса должен покрывать 3 расстояния вход–стоп.',
'На восходящем тренде закрытие ниже минимума предыдущих 24 свечей и возврат закрытием над этим уровнем в течение следующих 3 свечей. Стоп под минимумом всего эпизода.',
'Средняя EMA выше старшей и своего значения 10 свечей назад. Свеча касается средней EMA и закрывается выше максимума предыдущей свечи. Стоп под минимумом последних 5 свечей. Чистая цель не ниже 4R.'
];
const fmt=(v,n=2)=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('ru-RU',{minimumFractionDigits:n,maximumFractionDigits:n});
const time=v=>typeof v==='number'?v:Date.parse(v);
const dateLabel=(v,long=false)=>new Date(time(v)).toLocaleString('ru-RU',{timeZone:'UTC',day:'2-digit',month:'2-digit',...(long?{year:'numeric'}:{}),hour:'2-digit',minute:'2-digit'});
const COLORS={bg:'#111722',line:'#263040',muted:'#8e9bb0',green:'#39c9a5',red:'#ef7786',orange:'#ffb454',blue:'#70a7ff',cyan:'#5bd5e8',purple:'#b79bff'};
let baseline,result,chart=null,comparisons=[],ready=false,busy=false,dirty=false,jobCounter=0,activeTab='trades',page=0,chartEnd=0,visibleBars=110,equityMode='equity',hoverIndex=-1,drag=null,chartGeneration=0,selectedTrade=null;
const jobs=new Map(),worker=new Worker('worker.js');
function config(){const p={};for(const key of configKeys){const el=$(key);p[key]=el.type==='checkbox'?el.checked:numberKeys.includes(key)?Number(el.value):el.value}return p}
function checkConfig(){for(const key of configKeys){const el=$(key);if(!el.checkValidity()){document.querySelector('.settings').classList.add('expanded');el.reportValidity();throw Error('Проверьте выделенное поле')}}const p=config();if(p.start>p.end)throw Error('Начало теста должно быть раньше конца');if(p.rsiMin>p.rsiMax)throw Error('Минимум RSI должен быть не больше максимума');return p}
function status(text,error=false){$('runStatus').textContent=text;$('runStatus').classList.toggle('negative',error);$('runStatus').classList.toggle('dirty',dirty&&!error)}
function setBusy(on){busy=on;$('run').disabled=on||!ready;$('compare').disabled=on||!ready;$('run').textContent=on?'Расчёт…':'Запустить бэктест';$('reset').disabled=on;$('chartTF').disabled=on}
function request(type,extra={}){const id=++jobCounter;return new Promise((resolve,reject)=>{jobs.set(id,{resolve,reject,type});worker.postMessage({id,type,...extra})})}
worker.onmessage=event=>{const m=event.data;if(m.type==='progress'){status(m.message);return}if(m.type==='ready'){ready=true;$('dataStatus').textContent=`${fmt(m.count,0)} свечей · до 30.09.2026`;setBusy(false)}const job=jobs.get(m.id);if(!job)return;jobs.delete(m.id);m.type==='error'?job.reject(Error(m.message)):job.resolve(m)};
worker.onerror=()=>{ready=false;setBusy(false);status('Не удалось запустить расчёт. Обновите страницу.',true);for(const job of jobs.values())job.reject(Error('Ошибка расчёта'));jobs.clear()};
function selectTab(tab){activeTab=tab;for(const b of document.querySelectorAll('[data-tab]')){const on=b.dataset.tab===tab;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on));$('tab-'+b.dataset.tab).hidden=!on}}
function updateStrategy(){const k=Number($('strategy').value);$('strategyHint').textContent=hints[k-1];$('ruleTitle').textContent=`${String(k).padStart(2,'0')} · ${names[k-1]}`;$('ruleText').textContent=rules[k-1]}
function markDirty(){dirty=true;updateStrategy();status('Настройки изменены · нажмите «Запустить бэктест»');$('resultMeta').classList.add('dirty')}
function renderStats(){const s=result.summary;const metrics=[['Доходность',fmt(s.return_pct)+'%',s.return_pct>=0?'positive':'negative'],['Макс. просадка',fmt(s.max_dd_pct)+'%',''],['Profit factor',fmt(s.profit_factor),''],['Прибыльных',fmt(s.win_pct,1)+(s.win_pct==null?'':'%'),''],['Сделок',fmt(s.trades,0),'']];$('stats').innerHTML=metrics.map(([label,value,cls])=>`<div><span>${label}</span><strong class="${cls}">${value}</strong></div>`).join('');$('viewTitle').textContent=names[result.id-1];$('tradeCount').textContent=s.trades;$('resultPeriod').textContent=`${result.config.start.split('-').reverse().join('.')} — ${result.config.end.split('-').reverse().join('.')}`;$('resultMeta').textContent=`${fmt(result.config.capital,0)} USDT · риск ${fmt(result.config.risk)}% · цель ≥${fmt(Math.max(result.config.rr,result.id===3?3.5:result.id===10?4:3),1)}R`;$('resultMeta').classList.remove('dirty')}
function sortedTrades(){return result?[...result.trades].reverse():[]}
function renderTrades(){if(!result)return;const trades=sortedTrades(),pages=Math.max(1,Math.ceil(trades.length/12));page=Math.min(page,pages-1);$('tradesBody').innerHTML=trades.slice(page*12,page*12+12).map((t,i)=>`<tr data-trade="${page*12+i}"><td><button aria-label="Показать сделку ${dateLabel(t.entry_time,true)} на графике">${dateLabel(t.entry_time,true)}</button></td><td>${fmt(t.entry)}</td><td>${fmt(t.stop)}</td><td>${fmt(t.target)}</td><td>${t.reason==='target'?'Цель':t.reason==='end_of_data'?'Конец данных':t.reason==='gap_stop'?'Стоп / гэп':'Стоп'}</td><td class="${t.pnl>=0?'positive':'negative'}">${fmt(t.pnl)} USDT</td><td class="${t.net_r>=0?'positive':'negative'}">${fmt(t.net_r,2)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty-row">Нет сделок при этих условиях.</td></tr>';$('pageInfo').textContent=`${page+1} / ${pages} · ${trades.length} сделок`;$('prevPage').disabled=page===0;$('nextPage').disabled=page>=pages-1;if(!trades.length&&result.skipped){const skip=result.skipped;$('pageInfo').textContent=`${result.summary.signals} сигналов · RR: ${skip.rr} · сопротивление: ${skip.barrier} · структура: ${skip.impulse}`}}
function renderComparisons(){$('comparisonBody').innerHTML=comparisons.map(s=>`<tr data-strategy="${s.id}"><td><button>${String(s.id).padStart(2,'0')} · ${s.name}</button></td><td>${fmt(s.trades,0)}</td><td>${fmt(s.win_pct,1)}${s.win_pct==null?'':'%'}</td><td class="${s.return_pct>=0?'positive':'negative'}">${fmt(s.return_pct)}%</td><td>${fmt(s.max_dd_pct)}%</td><td>${fmt(s.profit_factor)}</td></tr>`).join('')}
async function execute(all=false){if(busy)throw Error('Дождитесь завершения текущей проверки');if(!ready)throw Error('Дождитесь загрузки истории');const p=checkConfig();setBusy(true);$('chartLoading').hidden=false;try{const m=await request(all?'compare':'run',{config:p,tf:$('chartTF').value});result=m.result;selectedTrade=null;dirty=JSON.stringify(config())!==JSON.stringify(p);page=0;chart=m.chart;chartEnd=chart.rows.length;hoverIndex=-1;renderStats();renderTrades();drawCharts();if(all){comparisons=m.comparisons;renderComparisons();$('comparisonNote').textContent=`Пересчитано для ${p.start} — ${p.end} · сигналы: ${p.signalTF==='auto'?'исходные таймфреймы':p.signalTF} · риск ${fmt(p.risk)}%. Нажмите стратегию для подробного теста.`;selectTab('comparison')}status(dirty?'Настройки изменились во время расчёта · результат для предыдущих значений':result.summary.trades?`Готово · ${result.tf} · ${result.summary.signals} сигналов · ${result.summary.trades} сделок`:`Готово · ${result.summary.signals} сигналов, допустимых сделок нет`);return result.summary}finally{setBusy(false);$('chartLoading').hidden=true}}
async function updateChart(){if(!ready||busy)return;const gen=++chartGeneration;$('chartLoading').hidden=false;try{const m=await request('chart',{config:result?result.config:defaultConfig,tf:$('chartTF').value});if(gen===chartGeneration){chart=m.chart;chartEnd=chart.rows.length;hoverIndex=-1;drawPrice()}}catch(e){status(e.message,true)}finally{if(gen===chartGeneration)$('chartLoading').hidden=true}}
function canvasContext(id){const el=$(id),rect=el.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2);el.width=Math.round(rect.width*ratio);el.height=Math.round(rect.height*ratio);const c=el.getContext('2d');c.scale(ratio,ratio);c.fillStyle=COLORS.bg;c.fillRect(0,0,rect.width,rect.height);c.font='12px "IBM Plex Mono",monospace';return {c,w:rect.width,h:rect.height}}
function linePath(c,rows,column,x,y,color,width=1){c.strokeStyle=color;c.lineWidth=width;c.beginPath();let drawing=false;rows.forEach((r,i)=>{const value=r[column];if(value==null){drawing=false;return}drawing?c.lineTo(x(i),y(value)):c.moveTo(x(i),y(value));drawing=true});c.stroke();c.lineWidth=1}
function drawPrice(){if(!chart||!chart.rows.length)return;const {c,w,h}=canvasContext('priceChart'),all=chart.rows,plotWidth=w-77,left=12;chartEnd=Math.max(Math.min(all.length,Math.round(chartEnd)),Math.min(all.length,visibleBars));const begin=Math.max(0,chartEnd-visibleBars),rows=all.slice(begin,chartEnd),barWidth=(plotWidth-left)/rows.length,osc=$('oscillator').value,oscH=osc==='none'?0:85,priceBottom=h-34-oscH,top=24,volumeH=$('showVolume').checked?45:0;
let low=Infinity,high=-Infinity;for(const r of rows){if(r[3]!=null)low=Math.min(low,r[3]);if(r[2]!=null)high=Math.max(high,r[2]);if($('showBB').checked){if(r[10]!=null)low=Math.min(low,r[10]);if(r[9]!=null)high=Math.max(high,r[9])}}
if(!Number.isFinite(low)||!Number.isFinite(high))return;const pad=Math.max((high-low)*.08,high*.0002);low-=pad;high+=pad;const x=i=>left+(i+.5)*barWidth,y=v=>top+(high-v)/(high-low)*(priceBottom-top-volumeH);
c.strokeStyle=COLORS.line;c.fillStyle=COLORS.muted;for(let j=0;j<5;j++){const v=low+(high-low)*j/4,yp=y(v);c.beginPath();c.moveTo(0,yp);c.lineTo(plotWidth,yp);c.stroke();c.fillText(fmt(v,0),plotWidth+8,yp+4)}
for(let i=0;i<rows.length;i+=Math.max(1,Math.floor(rows.length/5))){c.strokeStyle='#202b3b';c.beginPath();c.moveTo(x(i),0);c.lineTo(x(i),h-24);c.stroke();c.fillStyle=COLORS.muted;const label=new Date(rows[i][0]).toLocaleDateString('ru-RU',{timeZone:'UTC',day:'2-digit',month:'2-digit'});c.fillText(label,x(i)-18,h-9)}
if($('showVolume').checked){const maxVolume=Math.max(1,...rows.map(r=>r[5]||0));rows.forEach((r,i)=>{c.fillStyle=r[4]>=r[1]?'#39c9a533':'#ef778633';const height=(r[5]||0)/maxVolume*volumeH;c.fillRect(x(i)-barWidth*.3,priceBottom-height,Math.max(1,barWidth*.6),height)})}
rows.forEach((r,i)=>{if(r[1]==null||r[2]==null)return;const col=r[4]>=r[1]?COLORS.green:COLORS.red;c.strokeStyle=c.fillStyle=col;c.beginPath();c.moveTo(x(i),y(r[2]));c.lineTo(x(i),y(r[3]));c.stroke();c.fillRect(x(i)-Math.max(1,barWidth*.3),Math.min(y(r[1]),y(r[4])),Math.max(2,barWidth*.6),Math.max(1,Math.abs(y(r[1])-y(r[4]))))});
c.save();c.beginPath();c.rect(0,0,plotWidth,priceBottom-volumeH);c.clip();if($('showEMA').checked){linePath(c,rows,6,x,y,COLORS.orange,1.4);linePath(c,rows,7,x,y,COLORS.blue,1.4);linePath(c,rows,8,x,y,COLORS.purple,1.4)}if($('showBB').checked){linePath(c,rows,9,x,y,'#5bd5e8aa');linePath(c,rows,10,x,y,'#5bd5e8aa')}if($('showVWAP').checked)linePath(c,rows,11,x,y,'#e4d780',1.5);c.restore();
if(result&&$('showTrades').checked){for(const t of result.trades){for(const [timestamp,price,label,col]of [[time(t.entry_time),t.entry,'B',COLORS.blue],[time(t.exit_time)-1,t.exit,'×',t.pnl>=0?COLORS.green:COLORS.red]]){if(timestamp<rows[0][0]||timestamp>rows[rows.length-1][0]+chart.ms)continue;const i=searchRows(rows,timestamp)-1,j=Math.max(0,Math.min(rows.length-1,i));c.fillStyle=col;c.beginPath();c.arc(x(j),y(price),4,0,Math.PI*2);c.fill();c.font='bold 12px Arial';c.fillText(label,x(j)-4,y(price)+(label==='B'?17:-9));c.font='12px "IBM Plex Mono",monospace'}}}
if(osc!=='none'){const oTop=priceBottom+10,oBottom=h-28;c.strokeStyle=COLORS.line;c.beginPath();c.moveTo(0,oTop);c.lineTo(w,oTop);c.stroke();const col=osc==='rsi'?12:osc==='macd'?13:osc==='adx'?15:16,values=rows.map(r=>r[col]).filter(v=>v!=null);let mn=values.length?Math.min(...values):0,mx=values.length?Math.max(...values):1;if(osc==='rsi'){mn=0;mx=100}else if(osc==='adx'){mn=0;mx=Math.max(50,mx)}else if(osc==='macd'){const a=rows.map(r=>r[14]).filter(v=>v!=null);mn=Math.min(mn,0,...a);mx=Math.max(mx,0,...a)}if(mx===mn)mx=mn+1;const oy=v=>oTop+8+(mx-v)/(mx-mn)*(oBottom-oTop-17);if(osc==='rsi'){for(const v of [30,70]){c.setLineDash([3,4]);c.strokeStyle='#6a5574';c.beginPath();c.moveTo(0,oy(v));c.lineTo(plotWidth,oy(v));c.stroke();c.setLineDash([]);c.fillStyle=COLORS.muted;c.fillText(String(v),plotWidth+8,oy(v)+3)}}linePath(c,rows,col,x,oy,COLORS.purple,1.5);if(osc==='macd')linePath(c,rows,14,x,oy,COLORS.orange);c.fillStyle=COLORS.muted;c.fillText(osc.toUpperCase(),13,oTop+17);c.fillText(fmt(rows[rows.length-1][col],osc==='atr'||osc==='macd'?0:1),plotWidth+8,oTop+17)}
if(selectedTrade&&$('showTrades').checked&&time(selectedTrade.entry_time)>=rows[0][0]&&time(selectedTrade.entry_time)<=rows[rows.length-1][0]+chart.ms){for(const [key,col,label]of [['entry',COLORS.blue,'Вход'],['stop',COLORS.red,'Стоп'],['target',COLORS.green,'Цель']]){const v=selectedTrade[key],py=y(v);if(py>=top&&py<priceBottom-volumeH){c.strokeStyle=col;c.setLineDash([5,4]);c.beginPath();c.moveTo(x(Math.max(0,searchRows(rows,time(selectedTrade.entry_time))-1)),py);c.lineTo(plotWidth,py);c.stroke();c.setLineDash([]);c.fillStyle=col;c.fillText(label+' '+fmt(v,0),Math.max(10,plotWidth-120),py-5)}}}
const last=rows[rows.length-1];c.fillStyle=COLORS.muted;c.fillText(`${$('chartTF').value.toUpperCase()} · ${fmt(last[4])}`,13,17);let legend=$('overlayLegend');if(!legend){legend=document.createElement('div');legend.id='overlayLegend';legend.className='overlay-legend';canvas.parentElement.before(legend)}const p=result?.config||defaultConfig;legend.innerHTML=$('showEMA').checked?`<span style="color:${COLORS.orange}">EMA ${p.emaFast}</span><span style="color:${COLORS.blue}">EMA ${p.emaMid}</span><span style="color:${COLORS.purple}">EMA ${p.emaSlow}</span>`:'';
if(hoverIndex>=begin&&hoverIndex<chartEnd){const i=hoverIndex-begin;c.strokeStyle='#8e9bb099';c.setLineDash([4,4]);c.beginPath();c.moveTo(x(i),0);c.lineTo(x(i),h-24);c.stroke();c.setLineDash([])}
$('chartPosition').max=Math.max(0,all.length-visibleBars);$('chartPosition').value=Math.max(0,chartEnd-visibleBars);$('chartSubtitle').textContent=`${$('chartTF').value.toUpperCase()} · UTC`;$('candleInfo').textContent=`${dateLabel(rows[0][0])} — ${dateLabel(last[0])} · колесо: масштаб · перетаскивание: история`;
}
function searchRows(rows,t){let l=0,r=rows.length;while(l<r){const m=(l+r)>>>1;if(rows[m][0]<=t)l=m+1;else r=m}return l}
function drawEquity(){if(!result||!result.curve.length)return;const {c,w,h}=canvasContext('equityChart'),source=result.curve;let peak=result.config.capital;const points=source.map(([t,v])=>{peak=Math.max(peak,v);return [t,equityMode==='dd'?(v/peak-1)*100:v]});let mn=Math.min(...points.map(x=>x[1])),mx=Math.max(...points.map(x=>x[1]));if(equityMode==='dd')mx=Math.max(0,mx);const pad=Math.max((mx-mn)*.12,1);mn-=pad;mx+=pad;const left=12,right=w-85,top=8,bottom=h-25,t0=points[0][0],t1=points[points.length-1][0]||t0+1,x=t=>left+(t-t0)/Math.max(t1-t0,1)*(right-left),y=v=>top+(mx-v)/(mx-mn)*(bottom-top);c.strokeStyle=COLORS.line;for(let j=0;j<4;j++){const v=mn+(mx-mn)*j/3,py=y(v);c.beginPath();c.moveTo(0,py);c.lineTo(right,py);c.stroke();c.fillStyle=COLORS.muted;c.fillText(fmt(v,equityMode==='dd'?1:0)+(equityMode==='dd'?'%':''),right+9,py+4)}const gradient=c.createLinearGradient(0,top,0,bottom);gradient.addColorStop(0,equityMode==='dd'?'#ef778622':'#ffb45428');gradient.addColorStop(1,'#11172200');c.beginPath();c.moveTo(x(points[0][0]),bottom);points.forEach(([t,v])=>c.lineTo(x(t),y(v)));c.lineTo(x(points[points.length-1][0]),bottom);c.closePath();c.fillStyle=gradient;c.fill();c.strokeStyle=equityMode==='dd'?COLORS.red:COLORS.orange;c.lineWidth=1.7;c.beginPath();points.forEach(([t,v],i)=>i?c.lineTo(x(t),y(v)):c.moveTo(x(t),y(v)));c.stroke();c.lineWidth=1;for(let j=0;j<4;j++){const t=t0+(t1-t0)*j/3;c.fillStyle=COLORS.muted;c.fillText(new Date(t).toLocaleDateString('ru-RU',{timeZone:'UTC',month:'2-digit',year:'numeric'}),x(t)-18,h-7)}}
function drawCharts(){drawPrice();drawEquity()}
function showTrade(t){if(!chart)return;selectedTrade=t;const i=searchRows(chart.rows,time(t.entry_time))-1,exit=searchRows(chart.rows,time(t.exit_time));visibleBars=Math.min(800,Math.max(70,exit-i+35));chartEnd=Math.min(chart.rows.length,Math.max(visibleBars,exit+20));hoverIndex=i;drawPrice();$('priceChart').scrollIntoView({behavior:'smooth',block:'center'})}
function csvExport(){if(!result)return;const cols=['entry_time','entry','stop','target','qty','exit_time','exit','reason','pnl','net_r','equity_after'];const text='\uFEFF'+cols.join(',')+'\n'+result.trades.map(t=>cols.map(k=>k.endsWith('_time')?new Date(time(t[k])).toISOString():t[k]).join(',')).join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`BTCUSDT_strategy_${result.id}_${result.config.start}_${result.config.end}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('toggleSettings').addEventListener('click',()=>{const el=document.querySelector('.settings'),open=el.classList.toggle('expanded');$('toggleSettings').textContent=open?'Свернуть':'Настройки';$('toggleSettings').setAttribute('aria-expanded',String(open))});
for(const key of configKeys)$(key).addEventListener('change',markDirty);
for(const id of ['showEMA','showBB','showVWAP','showVolume','showTrades','oscillator'])$(id).addEventListener('change',drawPrice);
$('chartTF').addEventListener('change',updateChart);
$('run').addEventListener('click',()=>execute().catch(e=>status(e.message,true)));
$('compare').addEventListener('click',()=>execute(true).catch(e=>status(e.message,true)));
$('reset').addEventListener('click',()=>{for(const [key,v]of Object.entries(defaultConfig)){const el=$(key);el.type==='checkbox'?el.checked=v:el.value=v}markDirty();if(ready)execute().catch(e=>status(e.message,true))});
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>selectTab(b.dataset.tab)));
$('prevPage').addEventListener('click',()=>{page=Math.max(0,page-1);renderTrades()});$('nextPage').addEventListener('click',()=>{page++;renderTrades()});
$('tradesBody').addEventListener('click',e=>{const row=e.target.closest('[data-trade]');if(row)showTrade(sortedTrades()[Number(row.dataset.trade)])});
$('comparisonBody').addEventListener('click',e=>{const row=e.target.closest('[data-strategy]');if(row){$('strategy').value=row.dataset.strategy;markDirty();selectTab('trades');if(ready)execute().catch(err=>status(err.message,true))}});
$('export').addEventListener('click',csvExport);
$('latest').addEventListener('click',()=>{if(chart){chartEnd=chart.rows.length;hoverIndex=-1;drawPrice()}});
$('chartPosition').addEventListener('input',()=>{chartEnd=Number($('chartPosition').value)+visibleBars;drawPrice()});
$('equityMode').addEventListener('click',()=>{equityMode='equity';$('equityMode').classList.add('active');$('ddMode').classList.remove('active');drawEquity()});$('ddMode').addEventListener('click',()=>{equityMode='dd';$('ddMode').classList.add('active');$('equityMode').classList.remove('active');drawEquity()});
const canvas=$('priceChart');canvas.addEventListener('wheel',e=>{if(!chart)return;e.preventDefault();visibleBars=Math.max(25,Math.min(600,Math.round(visibleBars*(e.deltaY>0?1.17:.85))));drawPrice()},{passive:false});
canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,end:chartEnd};canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(!chart)return;const rect=canvas.getBoundingClientRect();if(drag){const delta=(e.clientX-drag.x)/Math.max(1,(rect.width-89)/visibleBars);chartEnd=drag.end-Math.round(delta);drawPrice();return}const begin=Math.max(0,chartEnd-visibleBars),i=begin+Math.floor((e.clientX-rect.left-12)/Math.max(1,(rect.width-89)/visibleBars));if(i<begin||i>=chartEnd){$('crosshair').hidden=true;return}hoverIndex=i;const r=chart.rows[i];$('crosshair').hidden=false;$('crosshair').textContent=`${dateLabel(r[0],true)} UTC\nO ${fmt(r[1])}  H ${fmt(r[2])}\nL ${fmt(r[3])}  C ${fmt(r[4])}\nRSI ${fmt(r[12],1)}  ATR ${fmt(r[16])}`;drawPrice()});
canvas.addEventListener('pointerup',()=>{drag=null});canvas.addEventListener('pointercancel',()=>{drag=null});canvas.addEventListener('pointerleave',()=>{if(!drag){hoverIndex=-1;$('crosshair').hidden=true;drawPrice()}});
new ResizeObserver(()=>drawCharts()).observe($('priceChart').parentElement);
async function init(){setBusy(false);updateStrategy();try{const r=await fetch('baseline.json');if(!r.ok)throw Error('История недоступна');baseline=await r.json();result={id:1,summary:baseline.summaries[0],trades:baseline.trades,curve:baseline.equity,config:{...defaultConfig},tf:'1h'};comparisons=baseline.summaries;chart={ms:3600000,rows:baseline.candles.map(r=>[...r,null,null,null,null,null,null,null,null])};chartEnd=chart.rows.length;renderStats();renderTrades();renderComparisons();drawCharts();await request('init');status(dirty?'История готова · примените изменённые настройки':'История готова · измените настройки и запустите тест');await updateChart()}catch(e){status(e.message,true)}}
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
register({name:'configure_bitcoin_backtest',title:'Настроить проверку BTC',description:'Изменяет видимые настройки проверки; не запускает расчёт.',inputSchema:{type:'object',properties:{strategy:{type:'integer',minimum:1,maximum:10},signalTF:{type:'string',enum:['auto','15m','1h','4h','1d']},start:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}$'},end:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}$'},rr:{type:'number',minimum:3,maximum:20},risk:{type:'number',minimum:.01,maximum:5}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(busy)throw Error('Расчёт уже выполняется');if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Ожидается объект');const old=config();try{for(const [key,v]of Object.entries(input)){if(!['strategy','signalTF','start','end','rr','risk'].includes(key))throw Error('Неизвестный параметр');$(key).value=v}checkConfig();markDirty();return {configured:config(),requiresRun:true}}catch(e){for(const [key,v]of Object.entries(old)){$(key).type==='checkbox'?$(key).checked=v:$(key).value=v}throw e}}});
register({name:'run_bitcoin_backtest',title:'Запустить проверку BTC',description:'Запускает выбранную стратегию с видимыми настройками и обновляет график и результат.',inputSchema:{type:'object',properties:{compareAll:{type:'boolean'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='compareAll')||(input.compareAll!==undefined&&typeof input.compareAll!=='boolean'))throw Error('Неверный параметр compareAll');return await execute(Boolean(input.compareAll))}});
register({name:'read_bitcoin_backtest_result',title:'Прочитать результат BTC',description:'Возвращает последний вычисленный результат и признак изменённых настроек.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(input&&Object.keys(input).length)throw Error('Параметры не поддерживаются');if(!result)throw Error('Результат ещё не загружен');return {summary:result.summary,settings:result.config,settingsChanged:dirty}}});
addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
init();

