/* Deterministic OHLCV backtesting. Shared by the browser worker and Node audit. */
(function(root){
'use strict';
const M=60000,D=86400000,TF={'15m':15*M,'1h':60*M,'4h':240*M,'1d':D};
const NAMES=['','Откат по тренду','Пробой и ретест','Сжатие волатильности','Ложный пробой минимума дня','Отскок в боковике','Возврат к VWAP','Пробой диапазона 00–06 UTC','Флаг после импульса','Неудачный пробой вниз','Дневной откат к EMA50'];
function array(n){return new Float64Array(n).fill(NaN)}
function lower(a,x){let l=0,r=a.length;while(l<r){let m=(l+r)>>>1;a[m]<x?l=m+1:r=m}return l}
function rolling(a,n,kind,shift=0){const out=array(a.length);let sum=0,count=0;for(let i=0;i<a.length;i++){if(Number.isFinite(a[i])){sum+=a[i];count++}if(i>=n&&Number.isFinite(a[i-n])){sum-=a[i-n];count--}if(i>=n-1&&count===n){let value=sum/n;if(kind==='min'||kind==='max'){value=kind==='min'?Infinity:-Infinity;for(let j=i-n+1;j<=i;j++)value=kind==='min'?Math.min(value,a[j]):Math.max(value,a[j])}if(i+shift<a.length)out[i+shift]=value}}return out}
function ewm(a,alpha,n){const out=array(a.length);let v=NaN,count=0,oldWeight=1;for(let i=0;i<a.length;i++){if(Number.isFinite(v))oldWeight*=1-alpha;if(Number.isFinite(a[i])){if(Number.isFinite(v)){v=(oldWeight*v+alpha*a[i])/(oldWeight+alpha);oldWeight=1}else v=a[i];count++}if(count>=n)out[i]=v}return out}
function agg(raw,ms){if(ms===TF['15m']){return {...raw,t:raw.t.map(x=>x+ms),complete:new Uint8Array(raw.t.length).fill(1),ms}}const t=[],o=[],h=[],l=[],c=[],v=[],q=[],count=[];let prev=-1,j=-1;for(let i=0;i<raw.t.length;i++){const bucket=Math.floor(raw.t[i]/ms)*ms;if(bucket!==prev){if(prev>=0)for(let missing=prev+ms;missing<bucket;missing+=ms){j++;t.push(missing+ms);o.push(NaN);h.push(NaN);l.push(NaN);c.push(NaN);v.push(0);q.push(0);count.push(0)}j++;t.push(bucket+ms);o.push(raw.o[i]);h.push(raw.h[i]);l.push(raw.l[i]);c.push(raw.c[i]);v.push(raw.v[i]);q.push(raw.q[i]);count.push(1);prev=bucket}else{h[j]=Math.max(h[j],raw.h[i]);l[j]=Math.min(l[j],raw.l[i]);c[j]=raw.c[i];v[j]+=raw.v[i];q[j]+=raw.q[i];count[j]++}}return {t:Float64Array.from(t),o:Float64Array.from(o),h:Float64Array.from(h),l:Float64Array.from(l),c:Float64Array.from(c),v:Float64Array.from(v),q:Float64Array.from(q),complete:Uint8Array.from(count.map(x=>x===ms/TF['15m']?1:0)),ms}}
function align(src,values,t){const out=array(t.length);let j=-1;for(let i=0;i<t.length;i++){while(j+1<src.length&&src[j+1]<=t[i])j++;if(j>=0)out[i]=values[j]}return out}
function indicator(d,p){const n=d.t.length,tr=array(n),up=new Float64Array(n),dn=new Float64Array(n),delta=array(n);for(let i=0;i<n;i++){tr[i]=i?Math.max(...[d.h[i]-d.l[i],Math.abs(d.h[i]-d.c[i-1]),Math.abs(d.l[i]-d.c[i-1])].filter(Number.isFinite)):d.h[i]-d.l[i];if(i){let a=d.h[i]-d.h[i-1],b=d.l[i-1]-d.l[i];up[i]=a>b&&a>0?a:0;dn[i]=b>a&&b>0?b:0;delta[i]=d.c[i]-d.c[i-1]}}
const atr=ewm(tr,1/p.atrPeriod,p.atrPeriod),plus=ewm(up,1/p.atrPeriod,p.atrPeriod),minus=ewm(dn,1/p.atrPeriod,p.atrPeriod),dx=array(n);for(let i=0;i<n;i++)dx[i]=100*Math.abs(plus[i]-minus[i])/(plus[i]+minus[i]);const adx=ewm(dx,1/p.atrPeriod,p.atrPeriod),gain=array(n),loss=array(n);for(let i=1;i<n;i++){gain[i]=Math.max(0,delta[i]);loss[i]=Math.max(0,-delta[i])}const g=ewm(gain,1/p.rsiPeriod,p.rsiPeriod),ls=ewm(loss,1/p.rsiPeriod,p.rsiPeriod),rsi=array(n);for(let i=0;i<n;i++)rsi[i]=ls[i]===0?100:100-100/(1+g[i]/ls[i]);
const mean=rolling(d.c,p.bbPeriod,'mean'),bbU=array(n),bbL=array(n),width=array(n);let sum=0,sq=0,count=0;for(let i=0;i<n;i++){if(Number.isFinite(d.c[i])){sum+=d.c[i];sq+=d.c[i]*d.c[i];count++}if(i>=p.bbPeriod&&Number.isFinite(d.c[i-p.bbPeriod])){sum-=d.c[i-p.bbPeriod];sq-=d.c[i-p.bbPeriod]**2;count--}if(i>=p.bbPeriod-1&&count===p.bbPeriod){let sd=Math.sqrt(Math.max(0,sq/p.bbPeriod-(sum/p.bbPeriod)**2));bbU[i]=mean[i]+p.bbMult*sd;bbL[i]=mean[i]-p.bbMult*sd;width[i]=2*p.bbMult*sd/mean[i]}}
const fast=ewm(d.c,2/13,12),slow=ewm(d.c,2/27,26),macd=array(n);for(let i=0;i<n;i++)macd[i]=fast[i]-slow[i];const macdSignal=ewm(macd,2/10,9);
const vwap=array(n);let key=-1,cv=0,cq=0;for(let i=0;i<n;i++){let day=Math.floor((d.t[i]-d.ms)/D);if(day!==key){key=day;cv=0;cq=0}cv+=d.v[i];cq+=d.q[i];vwap[i]=cq/cv}
return {...d,atr,adx,rsi,bbU,bbL,width,vwap,macd,macdSignal,emaFast:ewm(d.c,2/(p.emaFast+1),p.emaFast),emaMid:ewm(d.c,2/(p.emaMid+1),p.emaMid),emaSlow:ewm(d.c,2/(p.emaSlow+1),p.emaSlow),avgvol:rolling(d.v,20,'mean',1),highRange:rolling(d.h,p.lookback,'max',1),lowRange:rolling(d.l,p.lookback,'min',1)}}
const defaults={strategy:1,signalTF:'auto',trendTF:'auto',start:'2021-01-01',end:'2026-09-30',capital:10000,risk:.25,rr:3,buffer:.2,fee:.1,slip:.02,resistance:true,emaFast:20,emaMid:50,emaSlow:200,atrPeriod:14,adxMax:20,volumeFactor:1.5,lookback:48,bbPeriod:20,bbMult:2,rsiPeriod:14,rsiFilter:false,rsiMin:30,rsiMax:70};
function prepare(raw,p){const cache={};return {raw,p,get(tf){if(!cache[tf])cache[tf]=indicator(agg(raw,TF[tf]),p);return cache[tf]}}}
function makeSignals(ctx,k){const {raw,p}=ctx;const tf=p.signalTF==='auto'?([4,6,7].includes(k)?'15m':k===10?'1d':'1h'):p.signalTF;
const d=ctx.get(tf),n=d.t.length,day=ctx.get('1d'),trend=ctx.get(p.trendTF==='auto'?(k===7?'1h':'4h'):p.trendTF),trendC=align(trend.t,trend.c,d.t),trendM=align(trend.t,trend.emaMid,d.t),trendS=align(trend.t,trend.emaSlow,d.t),res=align(day.t,rolling(day.h,30,'max'),d.t),prevlow=align(day.t,day.l,d.t),prevhigh=align(day.t,day.h,d.t),low5=rolling(d.l,5,'min'),low3=rolling(d.l,3,'min'),high12=rolling(d.h,12,'max',1),low24=rolling(d.l,24,'min',1),signals=[];
const start=Date.parse(p.start+'T00:00:00Z'),end=Date.parse(p.end+'T00:00:00Z')+D;
function emit(i,stop,target=NaN,extra={}){if(!d.complete[i]||d.t[i]<start||d.t[i]>=end||!Number.isFinite(stop)||!Number.isFinite(d.atr[i]))return;if(p.rsiFilter&&!(d.rsi[i]>=p.rsiMin&&d.rsi[i]<=p.rsiMax))return;signals.push({time:d.t[i],stop,atr:d.atr[i],rr:Math.max(p.rr,k===3?3.5:k===10?4:3),target,resistance:res[i],...extra})}
let pending=null;
const session=[];if(k===7){let key=-1,hi=-Infinity,lo=Infinity,count=0;for(let i=0;i<raw.t.length;i++){let day0=Math.floor(raw.t[i]/D)*D;if(day0!==key){if(key>=0&&count>0)session.push([key+6*60*M,hi,lo]);key=day0;hi=-Infinity;lo=Infinity;count=0}if(raw.t[i]-day0<6*60*M){hi=Math.max(hi,raw.h[i]);lo=Math.min(lo,raw.l[i]);count++}}if(count>0)session.push([key+6*60*M,hi,lo])}
const sessionH=k===7?align(session.map(x=>x[0]),session.map(x=>x[1]),d.t):null;
for(let i=1;i<n;i++){const a=d.atr[i],wick=Math.min(d.o[i],d.c[i])-d.l[i],vol=d.v[i]>p.volumeFactor*d.avgvol[i],trendUp=trendC[i]>trendS[i];
if(k===1){let touch=false;for(let j=Math.max(0,i-4);j<=i;j++)if(d.l[j]<=d.emaFast[j]&&d.h[j]>=d.emaFast[j])touch=true;if(trendUp&&trendM[i]>trendS[i]&&touch&&d.c[i]>d.h[i-1])emit(i,low5[i]-p.buffer*a)}
if(k===2){if(pending){if(i>pending.i+6)pending=null;else if(d.l[i]<=pending.level+p.buffer*a&&d.h[i]>=pending.level-p.buffer*a&&d.c[i]>pending.level){emit(i,d.l[i]-p.buffer*a);pending=null}}if(d.c[i]>d.highRange[i]&&vol)pending={i,level:d.highRange[i]}}
if(k===3&&i>=200){const sample=Array.from(d.width.slice(i-181,i-1)).filter(Number.isFinite).sort((a,b)=>a-b);if(sample.length===180){const rank=(sample.length-1)*.2,threshold=sample[Math.floor(rank)]*(1-rank%1)+sample[Math.ceil(rank)]*(rank%1);if(d.width[i-1]<threshold&&d.c[i]>high12[i]&&vol)emit(i,d.l[i]-p.buffer*a)}}
if(k===4&&d.l[i]<prevlow[i]&&d.c[i]>prevlow[i]&&wick>=(d.h[i]-d.l[i])*.5)emit(i,d.l[i]-p.buffer*a,NaN,{barrier:prevhigh[i]});
if(k===5&&d.adx[i]<p.adxMax&&Math.abs(d.l[i]-d.lowRange[i])<=p.buffer*a&&d.c[i]>d.lowRange[i]&&d.c[i]<d.highRange[i]&&wick>=(d.h[i]-d.l[i])*.5)emit(i,d.l[i]-p.buffer*a,d.highRange[i]-p.buffer*a);
if(k===6&&d.adx[i]<p.adxMax&&d.l[i]<d.vwap[i]-2*a&&d.c[i]>d.h[i-1])emit(i,low3[i]-p.buffer*a,d.vwap[i]);
if(k===7){const hour=(d.t[i]%D)/(60*M);if(hour>=6&&hour<12&&d.c[i]>sessionH[i]&&d.c[i-1]<=sessionH[i]&&vol&&trendUp)emit(i,d.l[i]-p.buffer*a)}
if(k===8&&i>=12){for(let count=3;count<=8;count++){const j=i-count-1,size=d.c[j]-d.o[j-2];if(size<2*d.atr[j])continue;let peak=-Infinity,flaglo=Infinity,flaghi=-Infinity;for(let z=j-2;z<=j;z++)peak=Math.max(peak,d.h[z]);for(let z=j+1;z<i;z++){flaglo=Math.min(flaglo,d.l[z]);flaghi=Math.max(flaghi,d.h[z])}if(flaglo>=peak-.5*size&&d.c[i]>flaghi&&d.c[i-1]<=flaghi){emit(i,flaglo-p.buffer*a,NaN,{impulse:size});break}}}
if(k===9){if(pending){pending.lo=Math.min(pending.lo,d.l[i]);if(i>pending.i+3)pending=null;else if(d.c[i]>pending.level){if(trendUp)emit(i,pending.lo-p.buffer*a);pending=null}}if(!pending&&d.c[i]<low24[i]&&trendUp)pending={i,level:low24[i],lo:d.l[i]}}
if(k===10&&i>=10&&d.emaMid[i]>d.emaSlow[i]&&d.emaMid[i]>d.emaMid[i-10]&&d.l[i]<=d.emaMid[i]&&d.h[i]>=d.emaMid[i]&&d.c[i]>d.h[i-1])emit(i,low5[i]-p.buffer*a);
}return {signals,tf}}
function simulate(raw,signals,k,p){const fee=p.fee/100,slip=p.slip/100,risk=p.risk/100,start=Date.parse(p.start+'T00:00:00Z'),end=Date.parse(p.end+'T00:00:00Z')+D,first=lower(raw.t,start),last=lower(raw.t,end);let eq=p.capital,peak=eq,dd=0,pos=null,ambiguous=0;
const events=new Map();for(const s of signals){const i=lower(raw.t,s.time);if(raw.t[i]===s.time)events.set(i,s)}const used=new Set(),trades=[],curve=[[start,eq]],skipped={busy:0,invalid_stop:0,rr:0,barrier:0,impulse:0,one_per_day:0};
for(let i=first;i<last;i++){if(events.has(i)){const s=events.get(i),date=Math.floor(raw.t[i]/D);if(pos)skipped.busy++;else{const entry=raw.o[i]*(1+slip),stop=s.stop,unitrisk=entry*(1+fee)-stop*(1-slip)*(1-fee);if(stop>=raw.o[i]||unitrisk<=0)skipped.invalid_stop++;else if(k===7&&used.has(date))skipped.one_per_day++;else{const target=Number.isFinite(s.target)?s.target:(entry*(1+fee)+s.rr*unitrisk)/((1-slip)*(1-fee)),netrr=(target*(1-slip)*(1-fee)-entry*(1+fee))/unitrisk;
let blocked=p.resistance&&![5,6].includes(k)&&entry<s.resistance&&s.resistance<target;if(k===4)blocked=blocked||target>=s.barrier;
if(netrr+1e-8<s.rr)skipped.rr++;else if(blocked)skipped.barrier++;else if(k===8&&s.impulse<3*(entry-stop))skipped.impulse++;else{let qty=Math.min(eq*risk/unitrisk,eq/(entry*(1+fee)));pos={entry_time:raw.t[i],entry,stop,target,qty,risk_cash:qty*unitrisk,planned_rr:netrr,equity_before:eq};used.add(date)}}}}
if(pos){const both=raw.l[i]<=pos.stop&&raw.h[i]>=pos.target;if(both)ambiguous++;let price,reason;if(raw.o[i]>=pos.target){price=pos.target*(1-slip);reason='target'}else if(raw.o[i]<=pos.stop){price=raw.o[i]*(1-slip);reason='gap_stop'}else if(raw.l[i]<=pos.stop){price=pos.stop*(1-slip);reason='stop'}else if(raw.h[i]>=pos.target){price=pos.target*(1-slip);reason='target'}else if(i===last-1){price=raw.c[i]*(1-slip);reason='end_of_data'}if(reason){let pnl=pos.qty*(price*(1-fee)-pos.entry*(1+fee));eq+=pnl;trades.push({...pos,exit_time:raw.t[i]+TF['15m'],exit:price,reason,pnl,net_r:pnl/pos.risk_cash,equity_after:eq,ambiguous:both});pos=null}}
const mark=pos?eq+pos.qty*(raw.c[i]*(1-slip)*(1-fee)-pos.entry*(1+fee)):eq;peak=Math.max(peak,mark);dd=Math.max(dd,1-mark/peak);if((raw.t[i]+TF['15m'])%D===0||i===last-1)curve.push([raw.t[i]+TF['15m'],mark]);}
let gains=0,losses=0,wins=0,totalr=0;for(const t of trades){t.pnl>0?(gains+=t.pnl,wins++):losses-=t.pnl;totalr+=t.net_r}return {id:k,name:NAMES[k],signals:signals.length,trades,curve,skipped,summary:{id:k,name:NAMES[k],signals:signals.length,trades:trades.length,win_pct:trades.length?100*wins/trades.length:null,profit_factor:losses?gains/losses:null,return_pct:100*(eq/p.capital-1),max_dd_pct:100*dd,mean_r:trades.length?totalr/trades.length:null,ambiguous_bars:ambiguous,final_equity:eq},config:p}}
function validate(p){if(!TF[p.signalTF]&&p.signalTF!=='auto')throw Error('Неверный таймфрейм сигналов');if(!TF[p.trendTF]&&p.trendTF!=='auto')throw Error('Неверный таймфрейм тренда');if(p.start<'2021-01-01'||p.end>'2026-09-30'||p.start>p.end)throw Error('Выберите период внутри 01.01.2021–30.09.2026');const bounds={strategy:[1,10],capital:[100,1e7],risk:[.01,5],rr:[3,20],buffer:[0,5],fee:[0,1],slip:[0,1],emaFast:[2,100],emaMid:[5,200],emaSlow:[20,500],atrPeriod:[5,50],adxMax:[5,60],volumeFactor:[.5,5],lookback:[12,240],bbPeriod:[5,100],bbMult:[1,4],rsiPeriod:[5,50],rsiMin:[0,100],rsiMax:[0,100]};for(const [key,[lo,hi]]of Object.entries(bounds))if(!Number.isFinite(p[key])||p[key]<lo||p[key]>hi)throw Error(`Проверьте параметр ${key}: ${lo}–${hi}`);for(const key of ['strategy','emaFast','emaMid','emaSlow','atrPeriod','lookback','bbPeriod','rsiPeriod'])if(!Number.isInteger(p[key]))throw Error(`Параметр ${key} должен быть целым`);if(p.rsiMin>p.rsiMax)throw Error('Нижняя граница RSI должна быть меньше верхней');return p}
function readBinary(buffer){const a=new Float64Array(buffer),n=a.length/7;const raw={t:new Float64Array(n),o:new Float64Array(n),h:new Float64Array(n),l:new Float64Array(n),c:new Float64Array(n),v:new Float64Array(n),q:new Float64Array(n)};for(let i=0;i<n;i++){raw.t[i]=a[i*7];raw.o[i]=a[i*7+1];raw.h[i]=a[i*7+2];raw.l[i]=a[i*7+3];raw.c[i]=a[i*7+4];raw.v[i]=a[i*7+5];raw.q[i]=a[i*7+6]}return raw}
function chartData(ctx,tf){const d=ctx.get(tf),start=Date.parse(ctx.p.start+'T00:00:00Z'),end=Date.parse(ctx.p.end+'T00:00:00Z')+D;const fields=['t','o','h','l','c','v','emaFast','emaMid','emaSlow','bbU','bbL','vwap','rsi','macd','macdSignal','adx','atr'];return {ms:d.ms,columns:fields,rows:Array.from(d.t,(t,i)=>fields.map(key=>Number.isFinite(d[key][i])?(key==='t'?d[key][i]-d.ms:d[key][i]):null)).filter(row=>row[0]>=start&&row[0]<end)}}
const api={defaults,NAMES,TF,lower,rolling,agg,indicator,align,prepare,makeSignals,simulate,validate,readBinary,chartData};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.BitcoinEngine=api;
})(typeof self!=='undefined'?self:globalThis);

